---
title: "Portfolio"
author: ""
date: '`r format(Sys.time(), "%b %d, %Y")`'
output: html_document
---

- [Local Lion Data Analysis](./Projects/Local_Lion.html) *(Ongoing)*
    - My first real-world experience conducting data analysis! I've worked for Local Lion, a local donut and coffee shop, since 2013. Current production plans often result in a surplus of baked goods that must be disposed of every day. In order to motivate and guide my analysis, my initial plan is to create a model that could be used to predict the number of baked goods the shop must make on a given day in order to minimize loss.
  
- [Modeling Homes](./Projects/3851final.html) *(Spring 2018)*
    - Final project from Statistical Data Analysis II: modeling the price of homes.
  
- Intermediate Statistical Graphing in R *(Spring 2018)*
    - Reproduce the 2012 textbook *R Graphics Cookbook* by Winston Chang
    - [Chapter 2: Quickly Exploring Data](./Projects/R_cookbook/Chapter_2.html)
    - [Chapter 3: Bar Graphs](./Projects/R_cookbook/Chapter_3.html)
    - [Chapter 4: Line Graphs](./Projects/R_cookbook/Chapter_4.html)
    - [Chapter 5: Scatter Plots](./Projects/R_cookbook/Chapter_5.html)
    - [Chapter 6: Summarized Data Distributions](./Projects/R_cookbook/Chapter_6.html)
    - [Chapter 7: Annotations](./Projects/R_cookbook/Chapter_7.html)
    - [Chapter 8: Axes](./Projects/R_cookbook/Chapter_8.html)
    - [Chapter 9: Controlling the Overall Appearance of Graphs](./Projects/R_cookbook/Chapter_9.html)
    - [Chapter 10: Legends](./Projects/R_cookbook/Chapter_10.html)
    - [Chapter 11: Facets](./Projects/R_cookbook/Chapter_11.html)
    - [Chapter 12: Using Colors in Plots](./Projects/R_cookbook/Chapter_12.html)
    - [Chapter 13: Miscellaneous Graphs](./Projects/R_cookbook/Chapter_13.html)
  
- [Bicycle Sharing in Seattle](./Projects/Duplication_Project.html) *(Fall 2017)*
    - Final project for the Data Science I course -- reproduce Amber Thomas' [explorative analysis of bicycle-sharing data](https://amber.rbind.io/projects/2016/11/10/bicyclesseattle/).