---
title: "R Graphics Cookbook Chapter 11"
author: "NAME"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(ggplot2)
library(gcookbook)
```

## Facets

Note: Some problems cannot be completed as written because the code has changed. You will need to find the updated code.

### Section 11.1. Splitting Data into Subsets with Facets

```{r}
# Figure 11-1
p <- ggplot(mpg, aes(displ, hwy)) + geom_point()
p + facet_grid(drv ~ .)
p + facet_grid(. ~ cyl)
p + facet_grid(drv ~ cyl)

# Figure 11-2
p + facet_wrap( ~ class)
```

### Section 11.2. Using Facets with Different Axes

```{r}
# Figure 11-3
p + facet_grid(drv ~ cyl, scales = "free_y")
p + facet_grid(drv ~ cyl, scales = "free")
```

### Section 11.3. Changing the Text of Facet Labels

```{r}
# Figure 11-4
mpg2 <- mpg
levels(mpg2$drv)[levels(mpg2$drv)=="4"] <- "4wd"
levels(mpg2$drv)[levels(mpg2$drv)=="f"] <- "Front"
levels(mpg2$drv)[levels(mpg2$drv)=="r"] <- "Rear"
ggplot(mpg2, aes(displ, hwy)) + geom_point() + facet_grid(drv ~ .)

# Figure 11-5
ggplot(mpg2, aes(displ, hwy)) + geom_point() + 
  facet_grid(drv ~ ., labeller = label_both)
mpg3 <- mpg
levels(mpg3$drv)[levels(mpg2$drv)=="4"] <- "4^{wd}"
levels(mpg3$drv)[levels(mpg2$drv)=="f"] <- "- Front %.% e^{pi * i}"
levels(mpg3$drv)[levels(mpg2$drv)=="r"] <- "4^{wd} - Front"
```

### Section 11.4. Changing the Appearance of Facet Labels and Headers

```{r}
# Figure 11-6
ggplot(cabbage_exp, aes(Cultivar, Weight)) + geom_bar(stat = "identity") +
  facet_grid(. ~ Date) +
  theme(strip.text = element_text(face = "bold", size = rel(1.5)),
        strip.background = element_rect(fill = "lightblue", color = "black", size = 1))
```

<hr>
END!